baseURL = "http://ll-0013py.github.io/connect-with-me/"
languageCode = "en"
defaultContentLanguage = "en"

theme = "lynx"

title = "Connect with Me"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Ray"
  headline = "University student from Japan studying Computer Science and Data Science in Malaysia"
  image = "NGC133.jpg"

  links = [
    { twitter = "https://twitter.com/ll_0013py" },
    { twitter = { href = "https://twitter.com/ll_0013py", text = "Twitter (Music)" } },
    { instagram = { href = "https://www.instagram.com/ray_pianocover/", text = "Instagram" } },
    { youtube = "https://www.youtube.com/channel/UC6ljdPxxc12O3BMZzHnJWHg/?sub_confirmation=1" },
    { note-sticky-regular = { href = "https://note.com/ll_0013py/", text = "note" } },
    { box-open-solid = { href = "https://marshmallow-qa.com/ll_0013py?utm_medium=url_text&utm_source=promotion", text = "マシュマロ（質問箱）"} },
    { link = { href = "https://your_domain.com/", text = "ウェブサイト（準備中...）"} },
    { link = { href = "https://ll-0013py.github.io/portfolio", text = "Portfolio"} },
    { github = "https://github.com/ll-0013py" },
    { music-solid = { href = "https://store.piascore.com/publishers/5313", text = "Piascore"} },
    { music-solid = { href = "https://www.kokomu.jp/artist/ray?viewType=sheet&orderBy=createdAt&page=1", text = "kokomu"} },
    { music-solid = { href = "https://www.mymusicsheet.com/ray?viewType=sheet&orderBy=createdAt&page=1", text = "MyMusicSheet"} },
    { user-tie-solid = { href = "https://crowdworks.jp/public/employees/5702453", text = "CrowdWorks"} },
    { user-tie-solid = { href = "https://www.lancers.jp/profile/ll_0013py?ref=header_menu", text = "ランサーズ"} },
    { user-tie-solid = { href = "https://coconala.com/users/4454434/", text = "ココナラ"} },
    { email = "mailto:rr2024.web3@gmail.com" }
  ]


[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
