blank_issues_enabled: true
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/jpanther/lynx/discussions
    about: Request and discuss enhancements using GitHub Discussions
  - name: 🙋‍♀️ Question
    url: https://github.com/jpanther/lynx/discussions
    about: Please ask and answer general questions using GitHub Discussions
