baseURL = "http://ll-0013py.github.io/connect-with-me/"
languageCode = "en"
defaultContentLanguage = "en"

theme = "lynx"
googleAnalytics = "G-Y0RBR99HSF"

title = "Connect with Me"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Ray"
  headline = "University student from Japan studying Computer Science and Data Science in Malaysia"
  image = "NGC133.jpg"

  links = [
    { link = { href = "https://ray-globallife.com/", text = "My Website"} },
    { twitter = "https://twitter.com/ll_0013py" },
    { twitter = { href = "https://twitter.com/ray_pianocover", text = "Twitter (Music)" } },
    { instagram = { href = "https://www.instagram.com/ray_pianocover/", text = "Instagram" } },
    { youtube = "https://www.youtube.com/channel/UC6ljdPxxc12O3BMZzHnJWHg/?sub_confirmation=1" },
    { note-sticky-regular = { href = "https://note.com/ll_0013py/", text = "note" } },
    { box-open-solid = { href = "https://marshmallow-qa.com/ll_0013py?utm_medium=url_text&utm_source=promotion", text = "マシュマロ（質問箱）"} },
    { github = "https://github.com/ll-0013py" },
    { link = { href = "https://ll-0013py.github.io/portfolio", text = "Portfolio"} },
    { email = "mailto:rr2024.web3@gmail.com" }
  ]


[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
