name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Hugo site
        run: |
          # Your Hugo build command here

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: path/to/generated/files

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./public
